---
title: "BootStrap illustration of Central Limit Theorem"
author: "VAhir"
date: "June 5, 2016"
output: 
  html_document:
    keep_md: TRUE
---

# Central Limit Theorem  
**We will try and illustrate central limit theorem principles here.**  
* Given that a certain population does not have a normal distribution, when a sample is taken from such a population and mean is calculated for such a sample lets say 1000 times, the distribution of mean of such a sample distribution will mostly have Normal distribution.  
* The standard deviation of sampling distribution of sample means is smaller than standarad deviation of original sample standar deviation.  
* Sample size should be big enough to allow the mean distribution to be normal. Ideal value ~30.  
  
  
## Using a normal distribution sample
  
Lets take a sample of 30 using random normal distribution function.
We will record mean of this sample in m_sample1 variable and standard deviatio in sd_sample1.

```{R}
# Here i am setting seed so if it will be possible to reproduce same random sample dataset.
set.seed(6516)

# Random normal data set of size 30 stored into sample1
sample1 <- rnorm(30)

# Take mean of sample1
m_sample1 <- mean(sample1)

# Take standard deviation of sample1.
sd_sample1 <- sd(sample1)

```

Here if we take a historgram of the current sample, we may not necessarily get a normal distribution.

```{R}
hist(sample1, main="Histogram for Initial Sample (size 30)", xlab = "Initial Sample")
```

However, using bootstrap, if we take 1000 random samples from this same "sample1" with replace option as 'TRUE' and take mean of all of these 1000 random samples, the distribution of those means will turn out to be normally distributed. Lets try that.

```{R}

# Define an numeric array vector of size 1000 to store means of 1000 random samples.
reps <- 1000
bootsample <- numeric(reps)

# Run a for loop and store the means of 1000 samples in above defined vector.

for (i in 1:reps) { 
temp_sample <- sample(sample1, size=length(sample1), replace =TRUE)
bootsample[i] <- mean(temp_sample)
}

# Taking mean and standard deviation of 1000 means stored in boot sample.
m_bootsample <- mean(bootsample)
sd_bootsample_30 <- sd_sample1/sqrt(30)

# Displaying various values.
m_sample1
m_bootsample
sd_sample1
sd_bootsample_30

```
Above we can see that standard error gets smaller as sample size increases. We can calculate standard error by dividing standard deviation of original sample by square root of sample size.  
  
Now if we take a histogram of all these 1000 samples of means, we should get a normal distribution.

```{R}
# Create a histogram using means stored in bootsample to see if we get normal distribution.
hist(bootsample, main="Histogram of Means of Normal Sampling Distribution ", xlab="Means of Samples")

```

Now we will repeat the same process with a bigger sample size - lets say 50.

```{R}

# Repeating same process as we did for sample size 30.
set.seed(65162)
sample2 <- rnorm(50)
m_sample2 <- mean(sample2)
sd_sample2 <- sd(sample2)

for(i in 1:reps) { temp_sample <- sample(sample2, size=length(sample2), replace =TRUE)
bootsample[i] <- mean(temp_sample)
}

m_bootsample <- mean(bootsample)
sd_bootsample_50 <- sd_sample2/sqrt(50)

m_sample2
sd_sample2
m_bootsample
sd_bootsample_30
sd_bootsample_50

hist(sample2, main="Histogram for Initial Sample (size 50)", xlab = "Initial Sample") 
hist(bootsample, main="Histogram of Means of Normal Sampling Distribution ", xlab="Means of Samples")
```
  
  We can see in results that the standard error reduces when the sample size increases however the mean remains more or less the same as original sample mean.  
  
  
## Using a exponential distribution sample
  
  We are going to repeat the sample experiment of using boot strap mechanism to illustrate Central Limit Theorem but this time instead of using a random normal sample, we will use random exponential samples. We will take 2 samples of sizes 30 and 50.
  
**Sample Size 30 - Exponential**  
    
```{R}

# Here we will repeat the same process but instead of random normal dataset, we will use random exponential #dataset.
  set.seed(65163)
  sample1 <- rexp(30)
  m_sample1 <- mean(sample1)
  sd_sample1 <- sd(sample1)
  
  for (i in 1:reps) { 
temp_sample <- sample(sample1, size=length(sample1), replace =TRUE)
bootsample[i] <- mean(temp_sample)
}

m_bootsample <- mean(bootsample)
sd_bootsample_30 <- sd_sample1/sqrt(30)

m_sample1
m_bootsample
sd_sample1
sd_bootsample_30


# Creating histograms for original data set of size 30 and 1000 means of random sample out of same 30 dataset.

hist(sample1, main="Histogram of Initial Exponential Sample (size 30)", xlab = "Initial Sample")
hist(bootsample, main="Histogram of Means of Exponential Sampling Distribution ", xlab="Means of Samples")

```



**Sample Size 50 - Exponential**
```{R}
  set.seed(65164)
  sample1 <- rexp(50)
  m_sample1 <- mean(sample1)
  sd_sample1 <- sd(sample1)
  
  for (i in 1:reps) { 
temp_sample <- sample(sample1, size=length(sample1), replace =TRUE)
bootsample[i] <- mean(temp_sample)
}

m_bootsample <- mean(bootsample)
sd_bootsample_50 <- sd_sample1/sqrt(50)

m_sample1
m_bootsample

sd_sample1
sd_bootsample_30
sd_bootsample_50

hist(sample1, main="Histogram of Initial Exponential Sample (size 50)", xlab = "Initial Sample")
hist(bootsample, main="Histogram of Means of Exponential Sampling Distribution ", xlab="Means of Samples")

```

Above we can see that standard error gets smaller as sample size increases. We can calculate standard error by dividing standard deviation of original sample by square root of sample size. 
  
